// Generated by gencpp from file camera_msg/JointState.msg
// DO NOT EDIT!


#ifndef CAMERA_MSG_MESSAGE_JOINTSTATE_H
#define CAMERA_MSG_MESSAGE_JOINTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace camera_msg
{
template <class ContainerAllocator>
struct JointState_
{
  typedef JointState_<ContainerAllocator> Type;

  JointState_()
    : header()
    , left()
    , right()  {
    }
  JointState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(_alloc)
    , right(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _left_type;
  _left_type left;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::camera_msg::JointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_msg::JointState_<ContainerAllocator> const> ConstPtr;

}; // struct JointState_

typedef ::camera_msg::JointState_<std::allocator<void> > JointState;

typedef boost::shared_ptr< ::camera_msg::JointState > JointStatePtr;
typedef boost::shared_ptr< ::camera_msg::JointState const> JointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_msg::JointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_msg::JointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera_msg::JointState_<ContainerAllocator1> & lhs, const ::camera_msg::JointState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera_msg::JointState_<ContainerAllocator1> & lhs, const ::camera_msg::JointState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera_msg::JointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_msg::JointState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_msg::JointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_msg::JointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_msg::JointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_msg::JointState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_msg::JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73808776ee8064d08af80cf01bcc1b74";
  }

  static const char* value(const ::camera_msg::JointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73808776ee8064d0ULL;
  static const uint64_t static_value2 = 0x8af80cf01bcc1b74ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_msg::JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_msg/JointState";
  }

  static const char* value(const ::camera_msg::JointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_msg::JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"########################################\n"
"# Messages\n"
"########################################\n"
"Header header\n"
"float32[] left\n"
"float32[] right\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::camera_msg::JointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_msg::JointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_msg::JointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_msg::JointState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left[]" << std::endl;
    for (size_t i = 0; i < v.left.size(); ++i)
    {
      s << indent << "  left[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.left[i]);
    }
    s << indent << "right[]" << std::endl;
    for (size_t i = 0; i < v.right.size(); ++i)
    {
      s << indent << "  right[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.right[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MSG_MESSAGE_JOINTSTATE_H
